name: ft_e_buy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.4
  image_picker: ^0.8.6
  provider: ^6.0.4
  google_fonts: ^4.0.1
  dot_navigation_bar: ^1.0.1+4
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  favorite_button: ^0.0.3
  ionicons: ^0.1.2
  get: ^4.5.1
  firebase_core: ^2.4.0
  contactus: ^1.2.0
  url_launcher: ^6.1.7
  flutter_email_sender: ^5.2.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Illus-1.png
    - assets/images/Illus-2.png
    - assets/images/Illus-3.png
    - assets/images/Illus-4.png
    - assets/images/Illus-5.png
    - assets/images/Illus-6.png
    - assets/images/Illus-7.png
    - assets/images/login.png
    - assets/images/login_bottom.png
    - assets/images/main_bottom.png
    - assets/images/main_top.png
    - assets/images/signup_top.png
    - assets/images/singup.png
    - assets/images/user.jpeg
    - assets/images/logo.jpeg
    - assets/images/dress.png
    - assets/images/blouse.png
    - assets/images/contact.png

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf

